### ISSUE TITLE
FA icons appear unstyled for a short duration

### ISSUE THREAD

**Issue by dimitrisnl** [httptoolkit/httptoolkit.tech#1]
The font awesome icons lack styling for a short duration, [before the CSS gets applied during runtime.
](https://fontawesome.com/how-to-use/on-the-web/other-topics/server-side-rendering#css)
## Expected behaviour

The CSS rules should be present in the server-rendered content.

## Proposed solution

1. Stop FA from applying the styles during runtime

```js
// styles.js

fontawesome.config.autoAddCss = false;
```

2. Include them globally beforehand in `layouts/index.js`
```js
// layouts/index.js

import Header from '../components/header';
import Footer from '../components/footer';

import 'prismjs/themes/prism-tomorrow.css';
// adding
import '@fortawesome/fontawesome/styles.css';
```

Adding the styles in `gatsby-browser.js` should suffice but doesn't seem to be working in Gatsby v1.

## Example

![unnamed](https://user-images.githubusercontent.com/4951004/52135326-392bff00-264e-11e9-9233-0eb9c871cb39.gif)

## Elsewhere on GH

https://github.com/FortAwesome/react-fontawesome/issues/134

## Specifications

[whatsmybrowser.org/b/Q7HKKH7](https://whatsmybrowser.org/b/Q7HKKH7)

***

Would love to submit a PR if needed.

**Comment by pimterry** [comment]
Good spot! Thanks man :smile:

Now fixed, and I've helpfully moved to Gatsby v2 along the way as well, since I need it elsewhere. Thanks for pointing this out :+1:
