### ISSUE TITLE
ja3er

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit.tech#15]
I am the author of a JA3 library [1], and I am concerned with a recent post on the blog [2], namely:

> So it's not perfect, but we can differentiate a lot interesting clients here. You can check your own JA3 TLS fingerprint via ja3er.com, and you can search previously seen fingerprints and the associated user agents there too.

I would strongly advise against any mention of JA3er.com, as the site is currently producing provably invalid JA3 strings [3]. This is not ideal, as that site is the main (and possibly only) active repository of JA3 strings. Regardless, I would rather support valid information, than invalid information.

1. https://github.com/89z/parse/tree/master/crypto
2. https://httptoolkit.tech/blog/tls-fingerprinting-node-js
3. https://github.com/salesforce/ja3/issues/71

**Comment by pimterry** [comment]
Hi @89z. I hear what you're saying, but for the purposes of the article it doesn't really matter I think. I absolutely agree that isn't concerning that the database has invalid values, but it doesn't affect users who want to check their own JA3 fingerprint or look up other real fingerprints that they receive. The information in those cases, using real valid fingerprints, should be valid, and it's the only convenient site where you can do that.

Happy to change the URL if there is a good alternative JA3 database, but I haven't seen one. If you want to launch one, starting with the same data but with the invalid values filtered out then go for it! That'd be very welcome and I'd be happy to link to that instead.

**Comment by 89z** [comment]
Let me be clear, the site is producing provably invalid JA3 right now. This isnt something that was happening previously, its currently happening.

I just ran the tool myself, and first run looks OK:

~~~
771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0
~~~

but I tried again, and got a different, invalid JA3:

~~~
771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28,,
~~~

so if youre not concerned about that, then I cant force you to be. But to me, while its tempting to use the site, its a completely unreliable source of information, and should not be trusted or used.

**Comment by 89z** [comment]
FYI the JA3er site is dead now:

~~~
> curl -v ja3er.com
*   Trying 160.85.255.180:80...
* connect to 160.85.255.180 port 80 failed: Timed out
* Failed to connect to ja3er.com port 80 after 21060 ms: Timed out
* Closing connection 0
curl: (28) Failed to connect to ja3er.com port 80 after 21060 ms: Timed out
~~~
