### ISSUE TITLE
AndroGuard

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit.tech#16]
I see the post here mentions the tool JADX:

https://github.com/httptoolkit/httptoolkit.tech/blob/master/src/posts/android-reverse-engineering.md

that is a great tool, I just wanted to mention a similar one is available:

https://github.com/androguard/androguard

Personally I think JADX is better, but it never hurts to have options.

**Comment by pimterry** [comment]
Good point! I've added a note to the article: https://github.com/httptoolkit/httptoolkit.tech/commit/4cfab084e0c174ee3a02146e08356331d1997200.

Feel free to open PRs for articles in future if you think there's points that they're missing.

**Comment by 89z** [comment]
I just learned about a new one today:

https://github.com/google/android-classyshark

havent tried it, but thought you might be interested!
